// Code generated by "stringer -type=SystemType"; DO NOT EDIT.

package engine

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Initialize-0]
	_ = x[Update-1]
}

const _SystemType_name = "InitializeUpdate"

var _SystemType_index = [...]uint8{0, 10, 16}

func (i SystemType) String() string {
	if i < 0 || i >= SystemType(len(_SystemType_index)-1) {
		return "SystemType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _SystemType_name[_SystemType_index[i]:_SystemType_index[i+1]]
}
